### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by pendraggon87** [mitre-attack/attack-navigator#96] opened 2019-08-14 04:17 UTC
I receive the following errors when I try to install (after manually installing stream):

ubuntu@ip-172-31-40-75:~/attack-navigator/nav-app$ ng serve
Your global Angular CLI version (8.2.1) is greater than your local
version (8.0.1). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

Date: 2019-08-14T04:17:08.843Z
Hash: 3602851bdd684a79cb61
Time: 19173ms
chunk {main} main.js, main.js.map (main) 632 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 562 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 463 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 2.18 MB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 197 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.59 MB [initial] [rendered]

ERROR in ./node_modules/exceljs/dist/es5/csv/csv.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/exceljs/dist/es5/csv'
ERROR in ./node_modules/exceljs/dist/es5/utils/utils.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/exceljs/dist/es5/utils'
ERROR in ./node_modules/exceljs/dist/es5/xlsx/xlsx.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/exceljs/dist/es5/xlsx'
ERROR in ./node_modules/fast-csv/lib/index.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib'
ERROR in ./node_modules/fast-csv/lib/formatter/index.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib/formatter'
ERROR in ./node_modules/fast-csv/lib/formatter/formatter_stream.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib/formatter'
ERROR in ./node_modules/fast-csv/lib/formatter/formatter.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib/formatter'
ERROR in ./node_modules/fast-csv/lib/parser/index.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib/parser'
ERROR in ./node_modules/fast-csv/lib/parser/parser_stream.js
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib/parser'
ERROR in ./node_modules/fast-csv/lib/extended.js
Module not found: Error: Can't resolve 'os' in '/home/ubuntu/attack-navigator/nav-app/node_modules/fast-csv/lib'

**Comment by isaisabel** [comment] 2019-08-14 10:54
Hi @pendraggon87,

It looks like the `postinstall` step was not run. One of the following commands should fix your error:
1. `npm run postinstall`
2. `node patch-webpack.js`, which is the command postinstall would run anyway

Let me know if that works.

**Comment by isaisabel** [comment] 2019-08-14 10:54
Possible duplicate of #93.

**Comment by isaisabel** [comment] 2019-09-13 12:12
Closing due to lack of activity. If you're still having issues, let me know and I can reopen it.

**Closed by isaisabel** 2019-09-13 12:12 UTC
