### ISSUE TITLE
Will MITRE ATT&K ICS be added to the navigator?

### ISSUE THREAD

**Issue by KyyB** [mitre-attack/attack-navigator#229] opened 2020-09-10 19:55 UTC

**Comment by isaisabel** [comment] 2020-09-11 11:39
Hi @KyyB,

The ICS domain is not currently integrated into the greater ATT&CK infrastructure (thus its inclusion on a separate wiki). As it matures we may eventually move it over to the primary infrastructure, which would include the ATT&CK Navigator. We don't have any information on the timeframe of this integration at this moment.

**Comment by isaisabel** [comment] 2020-09-11 11:39
Duplicate of #126.

**Closed** 2020-09-11 11:39 UTC
Labels: duplicate

**Comment by isaisabel** [comment] 2020-10-28 13:15
Hi @KyyB,

Just wanted to quickly update you that ICS is now supported in the Navigator as of version 4.0.
