### ISSUE TITLE
Working on Navigator 4.3 Yesterday and JSON was parsed correctly, with v4.4 release today it is broken

### ISSUE THREAD

**Issue by beerMT** [mitre-attack/attack-navigator#354] opened 2021-09-15 19:34 UTC
I have a JSON layer that I've poured through numerous times now and I believe it is in accordance with the Layer 4.2 spec.

When I tried it with the v4.4 release today, I get the following parsing error:
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/6117308/133497096-bc2c0139-ce40-4829-89d1-cd2011309017.png">

When I look in dev tools, I see the following:
<img width="1579" alt="image" src="https://user-images.githubusercontent.com/6117308/133497412-30944803-9466-4672-ad27-71a01f91de34.png">

I've attached the JSON Nav layer that is producing this issue. When I run a test upload of a Threat Actor (admin@338) layer, I do not get this parsing error. So I'm leaning towards maybe something is off on the layer format I have used, but it was operational up to this release and I've gone line by line twice now for any key:value changes etc.

Thanks for the help/ideas!
[merged_techniques_used_by_groups_layer.json.zip](https://github.com/mitre-attack/attack-navigator/files/7172758/merged_techniques_used_by_groups_layer.json.zip)

**Comment by beerMT** [comment] 2021-09-15 19:53
Using same JSON layer file in wayback machine webpage
<img width="1894" alt="image" src="https://user-images.githubusercontent.com/6117308/133500292-64e24bc1-d67e-439c-aa10-458b075657b2.png">

**Comment by Th4nat0s** [comment] 2021-09-16 11:38
Same issue here...

for us it is related to "disabled" techniques which are generated like this.
When all disabled one the gui display it correctly.

```
 {
      "enabled": false,➠
      "techniqueID": "T1499.004"
    },➠
    {
      "enabled": false,➠
      "techniqueID": "T1560"
    },➠

```

I will manage to generate a sample broken one.

**Comment by isaisabel** [comment] 2021-09-16 11:44
Thanks for reaching out! We'll look into what's causing this and get a fix up ASAP.

**Comment by Th4nat0s** [comment] 2021-09-16 11:56
Here an example

![image](https://user-images.githubusercontent.com/1728186/133607322-9d394998-64ab-4bec-9d6f-43d549ae3dc1.png)

![image](https://user-images.githubusercontent.com/1728186/133607389-292669a9-8e1a-4a4d-9f7c-f35065919e9d.png)

The two file are attached.. 
[Archive.zip](https://github.com/mitre-attack/attack-navigator/files/7177461/Archive.zip)

Test enabled open flawlessly

**Comment by Th4nat0s** [comment] 2021-09-16 12:01
The disabled one also working fine from the wayback machine.

![image](https://user-images.githubusercontent.com/1728186/133608566-4580e726-325a-4580-8350-f7f6e8ff516c.png)

**Comment by isaisabel** [comment] 2021-09-16 12:22
Hi all,

I think this is actually related to the set of techniques defined in the layer. For some reason some (but not all) techniques are no longer recording their relevant tactics. When a layer loads where tactics are not explicitly defined for each technique, it can't infer which tactics _should_ be applied in those cases, causing the error.

Layers which explicitly define the tactic a given annotation applies to should still work, which is why we didn't catch this in testing.

**Comment by Th4nat0s** [comment] 2021-09-16 12:29
Thank's for your prompt debugging.

Yes, we don't generate the tactics in our dev. 
Until now the navigator was performing the necessary magic for us.

We don't precise the tactics for enabled either, since it was not mandatory in the file format.
https://github.com/mitre-attack/attack-navigator/blob/master/layers/LAYERFORMATv4_2.md
Amazingly it work for the enabled one. 

Do you plan to fix the navigator to follow the file format description it or should we plan refactor at our side ?

Have a nice day.

**Comment by isaisabel** [comment] 2021-09-16 12:30
@Th4nat0s Yeah it should be generating the tactics, the fact that it's not is a bug from the fact that tactics aren't loading properly.

The techniques where I'm seeing this bug are so far all deprecated or revoked -- e.g `T1065` in @beerMT's first layer which was revoked (replaced) by `T1571`. You wouldn't see these in the GUI anyway so I believe they must be a relic of layers that have been maintained across many releases of ATT&CK or generated without first filtering out deprecated and revoked techniques.

It's not explicitly stated that you can't include revoked/deprecated techniques in a layer, you just wouldn't expect to see them anyway since they aren't shown in the matrix. The Navigator shouldn't be crashing when trying to load them though, so this is still a bug.

**Comment by isaisabel** [comment] 2021-09-16 12:31
That's also why it's so inconsistent between layers -- it's dependant on you having both no tactics explicitly defined on a revoked or deprecated technique, which is a very specific set of circumstances.

**Comment by isaisabel** [comment] 2021-09-16 12:32
But regardless, this is definitely a bug on our end and not something that will require adjustment on your layers.

**Comment by Th4nat0s** [comment] 2021-09-16 12:36
Many thank's .. 

And thank you for your debugging, disabled tech.. should not be present in our json .. Some code is supposed to handle that :) ... 

Waiting for fix.

**Comment by isaisabel** [comment] 2021-09-16 14:18
This bug has been fixed in v4.4.1 (released a few minutes ago). The live instance has been updated as well and I can confirm the bug is fixed there as well.

If you run into any other trouble please don't hesitate to reach out!

**Closed by isaisabel** 2021-09-16 14:18 UTC
Labels: bug, priority/high, timescale/imminent, Points: 2

**Comment by beerMT** [comment] 2021-09-16 14:36
Wow @isaisabel , nicely done! Thanks so much for being responsive and helping to address that bug. Cheers!

**Comment by Th4nat0s** [comment] 2021-09-16 17:30
Thank's a lot !
