### ISSUE TITLE
Platforms filter is not working

### ISSUE THREAD

**Issue by marcusbakker** [mitre-attack/attack-navigator#245] opened 2020-10-30 20:00 UTC
Hi ATT&CK team,

When creating a layer file with a Filter object that has filters for specific ATT&CK platforms, it seems to be ignored when loaded into the Navigator.

If for example the attached file (`layer_network.json`) is loaded in the Navigator. All platforms are selected instead of only the `Network` platform.

[layer_network.json.zip](https://github.com/mitre-attack/attack-navigator/files/5467350/layer_network.json.zip)
```
{
	"name": "layer",
	"versions": {
		"attack": "8",
		"navigator": "4.0",
		"layer": "4.0"
	},
	"domain": "enterprise-attack",
	"description": "",
	"filters": {
		"platforms": [
			"Network"
		]
	},
	"sorting": 0,
	"layout": {
		"layout": "side",
		"showID": false,
		"showName": true
	},
	"hideDisabled": false,
	"techniques": [],
	"gradient": {
		"colors": [
			"#ff6666",
			"#ffe766",
			"#8ec843"
		],
		"minValue": 0,
		"maxValue": 100
	},
	"legendItems": [],
	"metadata": [],
	"showTacticRowBackground": false,
	"tacticRowBackground": "#dddddd",
	"selectTechniquesAcrossTactics": true,
	"selectSubtechniquesWithParent": false
}
```

<img width="158" alt="filters" src="https://user-images.githubusercontent.com/40516252/97751351-6ee76b80-1af2-11eb-87a0-65af33deaf6d.png">

Regards
Marcus

**Comment by isaisabel** [comment] 2020-11-09 13:19
This is an odd bug, it's definitely coded to deserialize the platforms[[1](https://github.com/mitre-attack/attack-navigator/blob/master/nav-app/src/app/viewmodels.service.ts#L1051), [2](https://github.com/mitre-attack/attack-navigator/blob/master/nav-app/src/app/viewmodels.service.ts#L1485-L1504)], but in testing it doesn't seem to actually apply them. 

This might be a bug from [loadVMData](https://github.com/mitre-attack/attack-navigator/blob/master/nav-app/src/app/viewmodels.service.ts#L405-L409), introduced when we changed the platform options to be dynamic (and not hardcoded). My guess is that `initPlatformOptions` is being called after the platforms are loaded from the layer, and are overwriting the selection. Further debugging is necessary to confirm if this is the cause.

**Comment by isaisabel** [comment] 2020-12-07 16:03
Fixed in the develop branch.

**Closed by isaisabel** 2020-12-07 16:03 UTC
Labels: bug, timescale/imminent
